/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlanoAlimentarRouteImport } from './routes/plano-alimentar'
import { Route as PacientesRouteImport } from './routes/pacientes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EvolucaoRouteImport } from './routes/evolucao'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as IndexRouteImport } from './routes/index'

const PlanoAlimentarRoute = PlanoAlimentarRouteImport.update({
  id: '/plano-alimentar',
  path: '/plano-alimentar',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesRoute = PacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EvolucaoRoute = EvolucaoRouteImport.update({
  id: '/evolucao',
  path: '/evolucao',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/evolucao': typeof EvolucaoRoute
  '/login': typeof LoginRoute
  '/pacientes': typeof PacientesRoute
  '/plano-alimentar': typeof PlanoAlimentarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/evolucao': typeof EvolucaoRoute
  '/login': typeof LoginRoute
  '/pacientes': typeof PacientesRoute
  '/plano-alimentar': typeof PlanoAlimentarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/evolucao': typeof EvolucaoRoute
  '/login': typeof LoginRoute
  '/pacientes': typeof PacientesRoute
  '/plano-alimentar': typeof PlanoAlimentarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/evolucao'
    | '/login'
    | '/pacientes'
    | '/plano-alimentar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/evolucao'
    | '/login'
    | '/pacientes'
    | '/plano-alimentar'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/evolucao'
    | '/login'
    | '/pacientes'
    | '/plano-alimentar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  EvolucaoRoute: typeof EvolucaoRoute
  LoginRoute: typeof LoginRoute
  PacientesRoute: typeof PacientesRoute
  PlanoAlimentarRoute: typeof PlanoAlimentarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/plano-alimentar': {
      id: '/plano-alimentar'
      path: '/plano-alimentar'
      fullPath: '/plano-alimentar'
      preLoaderRoute: typeof PlanoAlimentarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes': {
      id: '/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof PacientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evolucao': {
      id: '/evolucao'
      path: '/evolucao'
      fullPath: '/evolucao'
      preLoaderRoute: typeof EvolucaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  EvolucaoRoute: EvolucaoRoute,
  LoginRoute: LoginRoute,
  PacientesRoute: PacientesRoute,
  PlanoAlimentarRoute: PlanoAlimentarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
